### ISSUE TITLE
issues about custom 'NormalVectors' and TOF settings

### ISSUE THREAD

**Issue by Seanlam1124** [r-santo/openSSS#2]
Dear developers,
Thank you very much for your work. 

I encountered some issues when attempting to use custom scanner parameters.
In my understanding, the normalization factor corresponds to each Line of Response (LOR) for correcting the non-uniform detection efficiency of LORs. However, in your code, it seems to correspond to each crystal. Could you provide a more detailed explanation of 'NormVector' ?

If I currently do not have TOF info, can I directly remove the coefficients related to TOF when calculating the probability (in SingleScatterSimulationTOF)? For example, replace the formula 1 with formula 2.

1. Probability = GeometricalEfficiency*EnnergyEfficiency*KleinNishina(EnergyReferenceJoule,ScatterAngle)\*(AttenuationPath1*AttenuationScaled2*ActivityBinned1 + AttenuationPath2*ActivityBinned2*AttenuationScaled1);
2. Probability = GeometricalEfficiency*EnnergyEfficiency*KleinNishina(EnergyReferenceJoule,ScatterAngle)

Looking forward to your assistance. Thank you very much.

**Comment by Seanlam1124** [comment]
After examining the normfactor provided in the example, I noticed that it seems the normfactor for each sector is consistent. I am not sure if my understanding is correct—does this imply that your normalization is based on correcting for the angles of block detectors? Can this be transformed in a way that the normalization factor based on Lines of Response (LOR) is applicable to your program?

**Comment by r-santo** [comment]
Dear user,

Thank you for your interest in openSSS and pointing out some points requiring qualification.

To answer your first question, `NormalVectors` do not correspond to normalization factors, so they do not correct for the non-uniformity of the detectors efficiency. `NormalVectors` are actually the vectors normal to the face of each crystal. That is why for each sector, the values are all the same because the crystals have the same orientation. The normalization factors that you mention (correction for detector efficiency) can be applied after the scatters are estimated.
To give a simple example: in the case of detectors perfectly aligned in a circle, the `NormalVectors`  would all point to the center of the circle.

Regarding the second question, in the case of non-TOF, your proposed formula (remove the terms in the strikethrough quote bellow) is not correct. 

> Probability = GeometricalEfficiencyEnnergyEfficiencyKleinNishina(EnergyReferenceJoule,ScatterAngle)*~~(AttenuationPath1AttenuationScaled2ActivityBinned1 + AttenuationPath2ActivityBinned2AttenuationScaled1)~~;

This is because those terms include the activity and attenuation information of your measurement. They also include TOF information but you can track down in the code how that was introduced: it is a convolution of the TOF efficiency, the TOF bin and the integral over the LOR. So you can take only the last element for the non-TOF scenario, which is already exposed in a variable in the code as `ActivityPath`. Therefore, this solution should work:

`Probability = GeometricalEfficiency*EnnergyEfficiency*KleinNishina(EnergyReferenceJoule,ScatterAngle)*(AttenuationPath1*AttenuationScaled2*ActivityPath1 + AttenuationPath2*ActivityPath2*AttenuationScaled1);
`

In case you do not plan on using TOF at all in your application, there are further simplifications that can be made to optimize the code on computation time and memory efficiency.

**Comment by Seanlam1124** [comment]
Dear developers,
Thank you very much for your patient replies. I believe all my questions have been resolved.
