### ISSUE TITLE
Questions regarding the scaling factor

### ISSUE THREAD

**Issue by ZipaiWang** [r-santo/openSSS#4]
Dear Developer,

First, thank you very much for open-sourcing OpenSSS!

I am trying to estimate scatter for a GATE simulated scanner and apply scatter corrections in CASToR with list-mode OSEM. A geometry generator was made which outputs the geometry information in the same format as the generator provided by OpenSSS. Since I am using list-mode OSEM, I need a factor per LOR instead of per sinogram bin. To do so, I added a small converter inside the SingleScatterSimulationTOF() function so that while the function updates the scatter sinogram, it also updates my LOR matrix in the same way. Later, I times the scaling factor to my LOR matrix.

OpenSSS operates nicely in my case and can output a scatter map that is visually quite close (in terms of distribution) to the map generated using GATE ground-truth flags. However, I have a few questions about the scaling factor and the unit of the output scatter map.

1. I noticed that you multiply the sinogram by 1e10 in BackProjectionScatterRandFit(). May I ask why this is done? Is it because the sensitivity image results in a low estimated sinogram value?
2. CASToR in list-mode OSEM requires the scatter count rate in counts per second. What is the unit of the OpenSSS output scatter sinogram? And how can I convert it to count rate? (given the simulation duration)
3. If I would like to perform a non-TOF SSS estimation, is it correct to set the TOF bin number to 1?
4. Finally, is the IEEE-MIC presentation video available somewhere? I would like to watch it if possible.

Thank you very much! Any comments are highly appreciated!

Best regards,
Zipai

**Comment by r-santo** [comment]
Dear Zipai,

It is great to hear that the scatter maps from openSSS are visually quite close to those you obtain through GATE for your custom scanner geometry! Regarding your questions:

1.	Yes, you are correct. In the `BackProjectionScatterRandFit()` function, we noticed that the values for the scatter sinograms were very small in comparison to what is expected from measured prompts and as such, the fitting function we use from Matlab would give suboptimal results in some circumstances. We tried to correct for this by multiplying the estimated scatter sinogram by a large enough value (1e10)

2.	After scaling the scatters, the output of openSSS should be in the same units as the Prompts you used for scaling. So most probably, it will be in counts for your application so converting it into rate is simply a matter of dividing by the scanning duration.
However, depending on how you are using TOF within CASToR, you may require additional processing according to the CASToR documentation. If you have quantized TOF bins, you do not have to do anything else. If you have continuous TOF, you should divide the scatter rate by the size of each bin (in mm).

3.	For a non-TOF SSS estimation, you should be able to simply sum all your TOF bins. If you intend to perform a lot of non-TOF SSS estimations, it would be better to simplify the `SingleScatterSimulationTOF()` function by removing the TOF dependency, as it would make each estimation significantly faster. We have some code for this, so let us know if this is a feature you would like to be added.

4.	Regarding the presentation video, at some point it was available online exclusively for the attendees of the IEEE MIC 2023 conference. It may have been taken down already.

I would also like to note that your own implementation using a custom LOR matrix instead of sinograms is a good example of an improvement we would like to implement in a future version of openSSS, so as to more easily allow for mashing and irregular geometries. 
I hope you get to successfully reconstruct your simulated data, accurately corrected for scatters using openSSS.

Kind regards,
Rodrigo

**Comment by ZipaiWang** [comment]
Dear Rodrigo,

Thank you very much for your detailed answers!

Actually, the MIC video was taken down a few months after the conference. However, it would be extremely useful to read about the implementation, validations, and results of OpenSSS across the scanners. Sadly, the only thing available on IEEE is the one-paragraph abstract of the presentation.

I think the nonTOF version would be helpful for debugging, although most systems operate in TOF mode.

Anyway, I appreciate your kind help! and I want to keep this thread for a little bit longer for other potential questions.

Zipai

**Comment by r-santo** [comment]
Dear Zipai,

As we discussed, I have uploaded some functions for the non-TOF version of openSSS, which I hope helps with debugging.

Regarding more documentation on the openSSS project, we agree it would be useful for users and as such, we have been preparing a manuscript with detailed information. We will update the documentation accordingly, once it is ready.

Kind regards,
Rodrigo

**Comment by ZipaiWang** [comment]
Thank you so much Rodrigo!

With the non-TOF version, I figured out the problem I had before and successfully deployed TOF openSSS for our scatter correction. Thank you very much for all your kind help!


With best regards,
Zipai
